# Generated by Django 4.2.3 on 2023-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_purpose_alter_cv_address_alter_cv_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='age',
            field=models.PositiveIntegerField(default='25'),
            preserve_default=False,
        ),
    ]
